service:
  name: knowledge-api

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  Runtime: nodejs18.x
  region: ap-northeast-1

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
